# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'common' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for common

end

target 'ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for its

  pod 'SDWebImage', '4.4.2'
  pod 'MaterialComponents/ShadowElevations'

  target 'iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
